default_install_hook_types:
  - commit-msg
  - pre-commit
  - prepare-commit-msg
repos:
  - repo: >-
      https://gitlab.com/rs-devsecops/rs-dev/datagraph-and-content/code-standards-datagraph-and-content
    rev: 0.5.2
    hooks:
      - id: pre-commit-hooks-commit-message-linter
      - id: pre-commit-hooks-javascript-linter
version: 0.5.3
